/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-03-27 16:17:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/Header.jsp", Long.valueOf(1491890180000L));
    _jspx_dependants.put("/MainHeader.jsp", Long.valueOf(1491890180000L));
    _jspx_dependants.put("/GFooter.jsp", Long.valueOf(1491890180000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Golden Gym</title>\n");
      out.write("<link rel=\"icon\" href=\"photo's/goldenGym1.ico\" /><link rel=\"icon\" href=\"photo's/goldenGym1.ico\"  ></head>\n");
      out.write("<body>\n");
      out.write("	<header>");
      out.write('\n');
      out.write("<link rel=\"stylesheet\" href=\"css/w3.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"css/font-awesome-4.5.0/css/font-awesome.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />\n");
      out.write("<link src=\"css/GoldenGym.css\" type=\"text/css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<link rel=\"icon\" href=\"photo's/goldenGym1.ico\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-teal.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />	\n");
      out.write(" \n");
      out.write(" \n");
      out.write(" <!-- \n");
      out.write("<link href=\"css/w3-theme-blue.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />\n");
      out.write(" -->\n");
      out.write("<!-- \n");
      out.write("<link href=\"css/w3-theme-yellow.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />	\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-w3schools.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />	\n");
      out.write("\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-teal.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />	\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-red.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />	\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-purple.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />	\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-pink.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />	\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-orange.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />	\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-lime.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />	\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-light-green.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />	\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-light-blue.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />	\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-khaki.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />	\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-indigo.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />	\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-grey.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />	\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-green.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />	\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-deep-purple.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />\n");
      out.write("\n");
      out.write(" \n");
      out.write("<link href=\"css/w3-theme-dark-grey.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-cyan.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-brown.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />\n");
      out.write("	\n");
      out.write("<link href=\"css/w3-theme-blue.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-black.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("<link href=\"css/w3-theme-blue-grey.css\" rel=\"stylesheet\"\n");
      out.write("	type=\"text/css\" />\n");
      out.write(" -->\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"icon\" href=\"photo's/goldenGym1.ico\" />\n");
      out.write("<body onload=\"logoEffect()\">\n");
      out.write("	<img src=\"photo's/goldenGym.PNG\" id=\"logo\" height=\"100\" width=\"230\"\n");
      out.write("		class=\"w3-animate-top\" />\n");
      out.write("	\n");
      out.write("\n");
      out.write(" \n");
      out.write(" \n");
      out.write("<script src=\"js/jquery.min.js\"></script>\n");
      out.write("   \n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<noscript>\n");
      out.write("	<meta HTTP-EQUIV=\"Refresh\" CONTENT=\"0;URL=JavaScriptErrorPage.html\">\n");
      out.write("</noscript>\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("input {\n");
      out.write("	outline: 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("textarea {\n");
      out.write("	outline: 0px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	function logoEffect() {\n");
      out.write("		$(\"#logo\").css({\n");
      out.write("			\"transition\" : \"2s all\",\n");
      out.write("			\"transform\" : \"rotateY(360deg)\"\n");
      out.write("		});\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<nav class=\" navbar navbar-default w3-theme w3-card-8 w3-animate-top\">\n");
      out.write("		<div class=\"container-fluid \">\n");
      out.write("			<div class=\"navbar-header\">\n");
      out.write("				<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\n");
      out.write("					data-target=\"#myNavbar\">\n");
      out.write("					<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\n");
      out.write("						class=\"icon-bar\"></span>\n");
      out.write("				</button>\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n");
      out.write("				<ul class=\"nav navbar-nav\" id=\"menu\">\n");
      out.write("					<li><a href=\"index.jsp\" id=\"home\"><i class=\"fa-home fa\"\n");
      out.write("							style=\"font-size: 24px\"> Home</i></a></li>\n");
      out.write("					<li class=\"dropdown\" id=\"activity\"><a class=\"dropdown-toggle\"\n");
      out.write("						data-toggle=\"dropdown\" href=\"#\"><i class=\"fa fa-sitemap\"\n");
      out.write("							style=\"font-size: 24px\"> Activity</i><span class=\"caret\"></span></a>\n");
      out.write("						<ul class=\"dropdown-menu\">\n");
      out.write("							<li><a href=\"ActivityYoga.jsp\">Yoga</a></li>\n");
      out.write("							<li><a href=\"ActivityPranayam.jsp\">Pranayam</a></li>\n");
      out.write("							<li><a href=\"ActivityStretching.jsp\">Stretching</a></li>\n");
      out.write("							<li><a href=\"#\">CARDAIO</a></li>\n");
      out.write("						</ul></li>\n");
      out.write("					<li class=\"dropdown\" id=\"activity\"><a class=\"dropdown-toggle\"\n");
      out.write("						data-toggle=\"dropdown\" href=\"#\"><i class=\"fa-bolt fa\"\n");
      out.write("							style=\"font-size: 24px\"> Gym</i><span class=\"caret\"></span></a>\n");
      out.write("						<ul class=\"dropdown-menu\">\n");
      out.write("							<li class=\"w3-theme\"></li>\n");
      out.write("							<li><a href=\"Equipments.jsp\">Equipment</a></li>\n");
      out.write("							<li><a href=\"UserPackageListServlet\">Package</a></li>\n");
      out.write("							<li><a href=\"GuestScheduleListServlet\">Schedule</a></li>\n");
      out.write("							<li><a href=\"GuestTrainerIntro.jsp\">Trainer</a></li>\n");
      out.write("\n");
      out.write("						</ul></li>\n");
      out.write("\n");
      out.write("					<li id=\"About\"><a href=\"AboutUS.jsp\"><i class=\"fa-user fa\"\n");
      out.write("							style=\"font-size: 24px;\"> About Us</i></a></li>\n");
      out.write("					<li id=\"Contact\"><a href=\"Contact-us.jsp\"><i\n");
      out.write("							class=\"fa-phone fa\" style=\"font-size: 24px;\"> Contact Us</i></a></li>\n");
      out.write("				</ul>\n");
      out.write("				<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("					<li id=\"logIn\"><a href=\"LoginPage.jsp\"><span\n");
      out.write("							class=\"fa fa-lock\"></span> Login</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("	<script>\n");
      out.write("		$(document)\n");
      out.write("				.ready(\n");
      out.write("						function() {\n");
      out.write("							$(\n");
      out.write("									\"#home,#logIn ,  #activity ,#Equipment , #gym , #About ,#Contact , #member\")\n");
      out.write("									.mouseleave(function() {\n");
      out.write("										$(this).addClass(\"w3-theme \");\n");
      out.write("										$(this).css({\n");
      out.write("											\"transition\" : \"1s\"\n");
      out.write("										});\n");
      out.write("										$(this).removeClass(\"w3-card-16 \");\n");
      out.write("									});\n");
      out.write("\n");
      out.write("							$(\n");
      out.write("									\"#home,#logIn  , #activity ,#Equipment , #gym, #About ,#Contact , #member\")\n");
      out.write("									.mouseenter(\n");
      out.write("											function() {\n");
      out.write("												$(this).addClass(\n");
      out.write("														\"w3-white w3-card-16\");\n");
      out.write("												$(this).removeClass(\"w3-theme\");\n");
      out.write("											});\n");
      out.write("						});\n");
      out.write("	</script>");
      out.write("</header>\n");
      out.write("	<div class=\"w3-image w3-animate-opacity\">\n");
      out.write("		<!-- <img class=\"testimg\" src=\" photo's/gallery/gallery_66.jpg\"  alt=\"boat\"\n");
      out.write("			style=\"width: 100%; min-height: 550px; max-height: 700px;\">\n");
      out.write("		 -->\n");
      out.write("		\n");
      out.write("		<div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\" style=\"width: 100%; min-height: 550px; max-height: 700px;\">\n");
      out.write("					<!-- Indicators -->\n");
      out.write("					<ol class=\"carousel-indicators\">\n");
      out.write("						<li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("						<li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\n");
      out.write("						<li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\n");
      out.write("						<li data-target=\"#myCarousel\" data-slide-to=\"3\"></li>\n");
      out.write("						<li data-target=\"#myCarousel\" data-slide-to=\"4\"></li>\n");
      out.write("						<li data-target=\"#myCarousel\" data-slide-to=\"5\"></li>\n");
      out.write("						<li data-target=\"#myCarousel\" data-slide-to=\"6\"></li>\n");
      out.write("						<li data-target=\"#myCarousel\" data-slide-to=\"7\"></li>\n");
      out.write("						<li data-target=\"#myCarousel\" data-slide-to=\"8\"></li>\n");
      out.write("						<li data-target=\"#myCarousel\" data-slide-to=\"9\"></li>\n");
      out.write("					</ol>\n");
      out.write("					<!-- Wrapper for slides -->\n");
      out.write("					<div class=\" carousel-inner\" role=\"listbox\">\n");
      out.write("						<div class=\"item active \">\n");
      out.write("							<img\n");
      out.write("								src=\"photo's/gallery/gallery_66.jpg\" style=\"width: 100%; min-height: 550px; max-height: 700px;\"\n");
      out.write("								alt=\"Chania\" />\n");
      out.write("						</div>\n");
      out.write("						<div class=\"item\">\n");
      out.write("							<img src=\"photo's/gallery/gallery_5.jpg\" alt=\"Chania\"style=\"width: 100%; min-height: 550px; max-height: 700px;\" />\n");
      out.write("						</div>\n");
      out.write("						<div class=\"item\">\n");
      out.write("							<img src=\"photo's/gallery/gallery_4.jpg\" alt=\"Flower\"style=\"width: 100%; min-height: 550px; max-height: 700px;\" />\n");
      out.write("						</div>\n");
      out.write("						<div class=\"item\">\n");
      out.write("							<img src=\"photo's/gallery/gallery_11.jpg\"\n");
      out.write("								alt=\"Flower\" style=\"width: 100%; min-height: 550px; max-height: 700px;\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"item\">\n");
      out.write("							<img src=\"photo's/gallery/gallery_44.jpg\"\n");
      out.write("								alt=\"Flower\" style=\"width: 100%; min-height: 550px; max-height: 700px;\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"item\">\n");
      out.write("							<img\n");
      out.write("								src=\"photo's/gallery/gallery_55.jpg\"\n");
      out.write("								alt=\"Flower\" style=\"width: 100%; min-height: 550px; max-height: 700px;\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"item\">\n");
      out.write("							<img\n");
      out.write("								src=\"photo's/gallery/gallery_77.png\"\n");
      out.write("								alt=\"Flower\" style=\"width: 100%; min-height: 550px; max-height: 700px;\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"item\">\n");
      out.write("							<img src=\"photo's/gallery/gallery_88.jpg\" alt=\"Flower\" style=\"width: 100%; min-height: 550px; max-height: 700px;\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"item\">\n");
      out.write("							<img src=\"photo's/gallery/gallery_120.jpg\" alt=\"Flower\" style=\"width: 100%; min-height: 550px; max-height: 700px;\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"item\">\n");
      out.write("							<img src=\"photo's/gallery/gallery_1.jpg\" alt=\"Flower\" style=\"width: 100%; min-height: 550px; max-height: 700px;\">\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<!-- Left and right controls -->\n");
      out.write("					<a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\"\n");
      out.write("						data-slide=\"prev\"> <span\n");
      out.write("						class=\"fa-hand-o-left fa glyphicon glyphicon-chevron-left\"\n");
      out.write("						aria-hidden=\"true\"></span> <span class=\"sr-only\">Previous</span> </a>\n");
      out.write("					<a class=\"right carousel-control\" href=\"#myCarousel\" role=\"button\"\n");
      out.write("						data-slide=\"next\"> <span\n");
      out.write("						class=\"fa-hand-o-right fa glyphicon glyphicon-chevron-right\"\n");
      out.write("						aria-hidden=\"true\"></span> <span class=\"sr-only\">Next</span> </a>\n");
      out.write("				</div>\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		<div class=\"w3-title w3-margin-64\">\n");
      out.write("			<a href=\"#\" data-toggle=\"modal\" data-target=\"#btnformodel\"\n");
      out.write("				class=\"w3-animate-opacity w3-btn w3-xlarge w3-theme\"\n");
      out.write("				title=\"Go To gym\">It's Time To Go Golden Gym</a>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write(" 	<div class=\"w3-container 	jumbotron w3-card-8\">\n");
      out.write("		<div class=\"w3-row\" align=\"center\"\n");
      out.write("			style=\"font-size: 30px; color: purple; white-space: 5px; font-weight: 500;\">KEY\n");
      out.write("			FEATURES OF OUR CLOUD GOLDEN GYM</div>\n");
      out.write("		<div class=\"w3-row\">\n");
      out.write("			<p>Our gym management software makes it easier to process\n");
      out.write("				payments,Progress Card, monitor membersâ performance with Advanced\n");
      out.write("				Workout Tracking and stay in touch with your members. As soon you\n");
      out.write("				join the Golden Gym Family, you will gain instant access to superior\n");
      out.write("				online Feedback. Best yet, you will receive one-on-one training\n");
      out.write("				sessions with an Onboarding coach so you can begin using our Golden\n");
      out.write("				Gym to its full potential.</p>\n");
      out.write("			<p>Discover how our gym features help you gain more time. and get\n");
      out.write("				back to motivating your clients and building your gym. Stop worrying\n");
      out.write("				about administrative management tasks.</p>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"w3-container \">\n");
      out.write("		<div class=\"w3-half jumbotron \">\n");
      out.write("			<div class=\"w3-row\">\n");
      out.write("				<h3 style=\"color: purple\">Stress-Free Gym Billing</h3>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"w3-row\">\n");
      out.write("				<p>Golden Gym and automates your payment processing tasks to\n");
      out.write("					save you time and money. With our integrated payment processing,\n");
      out.write("					which is included in our monthly price*, you can easily send out\n");
      out.write("					billing reminders, invoices and receipts with automated emails, and\n");
      out.write("					collect payments more efficiently.</p>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("		<div class=\"w3-half jumbotron \">\n");
      out.write("			<div class=\"w3-row\">\n");
      out.write("				<h3 style=\"color: purple\">Gym Reservation System</h3>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"w3-row\">\n");
      out.write("				<p>Convenient online calendar and self-scheduling tools make it\n");
      out.write("					easy for new and current members to see what classes and events\n");
      out.write("					youâre offering, choose what works best for them and register\n");
      out.write("					quickly. Once in the gym, members can easily check-in through our\n");
      out.write("					Scheduling.</p>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"w3-container \">\n");
      out.write("		<div class=\"w3-half jumbotron \">\n");
      out.write("			<div class=\"w3-row\">\n");
      out.write("				<h3 style=\"color: purple\">Simplified Scheduling</h3>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"w3-row\">\n");
      out.write("				<p>From group fitness classes to boot camps and TRX sessions,\n");
      out.write("					keeping track of your gymâs updated schedule can be a daunting\n");
      out.write("					task. Our online scheduling simplifies even the toughest schedules,\n");
      out.write("					and will enable you to embed your new and improved schedule on your\n");
      out.write("					gymâs website and Facebook page.</p>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("		<div class=\"w3-half jumbotron \">\n");
      out.write("			<div class=\"w3-row\">\n");
      out.write("				<h3 style=\"color: purple\">Digital Workout Tracking</h3>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"w3-row\">\n");
      out.write("				<p>With our integrated Workout Tracker, using Excel to track\n");
      out.write("					your membersâ progress becomes a thing of the past. Our solution\n");
      out.write("					monitors attendance and tracks specific workout results directly to\n");
      out.write("					each memberâs personal profile. With the click of a button, easily\n");
      out.write("					see whoâs making progress towards their goals and who needs extra\n");
      out.write("					instruction.</p>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Login -->\n");
      out.write("	<div class=\"modal fade\" id=\"btnformodel\" role=\"dialog\">\n");
      out.write("		<div class=\"modal-dialog\">\n");
      out.write("\n");
      out.write("			<!-- Modal content-->\n");
      out.write("			<div class=\"modal-content w3-animate-left\">\n");
      out.write("				<div class=\"modal-header\">\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("					<h4 class=\"modal-title\">\n");
      out.write("						<i class=\"fa-user fa\"></i> Login Here\n");
      out.write("					</h4>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-body\">\n");
      out.write("					<div class=\"w3-container\">\n");
      out.write("						<div class=\"w3-row\">\n");
      out.write("							<div class=\"w3-col m5\">\n");
      out.write("								Click Here for &nbsp;<a href=\"LoginPage.jsp\"> <span class=\"w3-theme w3-btn\"><i\n");
      out.write("									class=\"fa-lock fa\"></i> Login in</span></a>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<br />\n");
      out.write("						 \n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-footer\">\n");
      out.write("					<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<footer>");
      out.write("\n");
      out.write("<footer class=\"w3-container w3-theme-d4\">\n");
      out.write("	<div class=\"w3-row\"\n");
      out.write("		style=\"font-family: cursive; font-stretch: wider; font-size: 25px;\">\n");
      out.write("		<div class=\"w3-col m3\">&nbsp; Gym</div>\n");
      out.write("		<div class=\"w3-col s1\">&nbsp;</div>\n");
      out.write("		<div class=\"w3-col m2 \">\n");
      out.write("			<i class=\"fa fa-sitemap\"></i> Activity\n");
      out.write("		</div>\n");
      out.write("		<div class=\"w3-col s1\">&nbsp;</div>\n");
      out.write("		<div class=\"w3-col m2 \">\n");
      out.write("			");

				if (session.getAttribute("memberBean") == null
						&& session.getAttribute("adminBean") == null
						&& session.getAttribute("trainerBean") == null) {
			
      out.write("\n");
      out.write("			<i class=\"fa fa-phone\"></i> <a href=\"Contact-us.jsp\"\n");
      out.write("				style=\"cursor: help;\"> Contact Us</a>\n");
      out.write("			");

				} else if (session.getAttribute("trainerBean") != null) {
			
      out.write("\n");
      out.write("			<i class=\"fa fa-phone\"></i> <a href=\"TrainerContact-US.jsp\"\n");
      out.write("				style=\"cursor: help;\"> Contact Us</a>\n");
      out.write("			 		\n");
      out.write("			 		");
} 
      out.write("\n");
      out.write("			 		</div>\n");
      out.write("		<div class=\"w3-col s1\">&nbsp;</div>\n");
      out.write("		<div class=\"w3-col m2\">\n");
      out.write("			<a href=\"AboutUS.jsp\"><i class=\"fa-group fa\"></i> About Us</a>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"w3-row\" style=\"font-family: cursive; font-stretch: wider;\">\n");
      out.write("		<div class=\"w3-col m3 \">\n");
      out.write("			&nbsp;<a href=\"Equipments.jsp\"> Equipment</a>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"w3-col s1\">&nbsp;</div>\n");
      out.write("		<div class=\"w3-col m2 \">\n");
      out.write("			<a href=\"AboutUS.jsp\">Yoga</a>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"w3-col s1\">&nbsp;</div>\n");
      out.write("		<div class=\"w3-col m2 \">&nbsp;</div>\n");
      out.write("		<div class=\"w3-col s1\">&nbsp;</div>\n");
      out.write("		<div class=\"w3-col m2 \">&nbsp;</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"w3-row\" style=\"font-family: cursive; font-stretch: wider;\">\n");
      out.write("		<div class=\"w3-col m3 \">\n");
      out.write("			&nbsp;<a href=\"GuestTrainerIntro.jsp\"> Trainers</a>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"w3-col s1\">&nbsp;</div>\n");
      out.write("		<div class=\"w3-col m2 \">\n");
      out.write("			<a href=\"#\">Pranayam</a>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"w3-row\" style=\"font-family: cursive; font-stretch: wider;\">\n");
      out.write("		<div class=\"w3-col m3 \">\n");
      out.write("			<a href=\"#\"> &nbsp; Schedule</a>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"w3-col s1\">&nbsp;</div>\n");
      out.write("		<div class=\"w3-col m2 \">\n");
      out.write("			<a href=\"#\">Stretching</a>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"w3-row\" style=\"font-family: cursive; font-stretch: wider;\">\n");
      out.write("		<div class=\"w3-col m3 \">&nbsp;</div>\n");
      out.write("		<div class=\"w3-col s1\">&nbsp;</div>\n");
      out.write("		<div class=\"w3-col m2 \">\n");
      out.write("			<a href=\"#\">ABS</a>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"w3-row\" style=\"font-family: cursive; font-stretch: wider;\">\n");
      out.write("		<div class=\"w3-col m3 \">&nbsp;</div>\n");
      out.write("		<div class=\"w3-col s1\">&nbsp;</div>\n");
      out.write("		<div class=\"w3-col m2 \">\n");
      out.write("			<a href=\"#\">CARDAIO</a>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("	</footer>\n");
      out.write("		 \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
